# Use a base image with a Java Runtime Environment (JRE)
FROM openjdk:17-jdk-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the built JAR file into the container
COPY target/bff-0.0.1-SNAPSHOT.jar /app

# Expose the port your Spring Boot application listens on (e.g., 8080)
EXPOSE 8080

# Define the command to run your Spring Boot application when the container starts
ENTRYPOINT ["java", "-jar", "bff-0.0.1-SNAPSHOT.jar"]